version: '2'

services:
  mounterest:
    container_name: mounterest
    image: asyrjasalo/mounterest:0.1.2
    command: --loglevel info
    environment:
      - HOST_UID
      - HOST_GID
    ports:
      - 2525:2525
      - 8273:8273
