version: '2'

services:
  mounterest:
    container_name: mounterest
    image: $MR_IMAGE_LABEL:$MR_IMAGE_TAG
    command: $MR_ARGS
    environment:
      - HOST_UID
      - HOST_GID
    ports:
      - $MB_PORT:2525
      - $MR_PORT:8273
